### ISSUE TITLE
Cronograma geral

### ISSUE THREAD

**Issue by amandahenriques** [G7-PI2-esteira-reabilitacao/Gerenciamento#6]
Fazer o cronograma com milestones

**Comment by dudagalvao19** [comment]
<iframe src="https://view.monday.com/embed/1576309121-f31400fc341910b3914098899ff0fce3?r=use1" width=770 height=500 style="border: 0; box-shadow: 5px 5px 56px 0px rgba(0,0,0,0.25);"></iframe>

**Comment by dudagalvao19** [comment]
https://view.monday.com/1576309121-f31400fc341910b3914098899ff0fce3?r=use1

**Comment by dudagalvao19** [comment]
![Cronograma](https://user-images.githubusercontent.com/48866832/129815412-c101f768-0bf9-46ed-8f95-c99b7ac6d5c1.png)
